/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cs404_project;

import javax.swing.JFileChooser;
import java.io.FileReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.isti.util.IstiFileFilter;

//MySQL imports (http://zetcode.com/db/mysqljava/)
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;

import javax.swing.*;
import java.awt.event.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

// password encryption stuff
import java.io.UnsupportedEncodingException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.PBEParameterSpec;

import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;
/**
 *
 * @author KJSFA1
 */

public class LogParser extends javax.swing.JFrame {
    
    private String filename = "";
    HashMap<String,String> badusers = new HashMap<>();  // Hash(user,IP) for bad users.
                                                        // Make this global for the CSV
                                                        // export button...

    DBConnectSettingsDialog jdlg_dbSettings;
    /**
     * Creates new form LogParser
     */
    public LogParser() {
        
        initComponents();
        jdlg_dbSettings = new DBConnectSettingsDialog ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OwnCloud Failed Logon Parser");

        jButton1.setLabel("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);

        jButton2.setText("Execute");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "IP Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jTextField2.setText("3");

        jLabel1.setText("failed logons within");

        jTextField3.setText("5");

        jLabel2.setText("minutes");

        jLabel3.setText("   ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setEnabled(false);
        jLabel3.setFocusable(false);

        jLabel4.setText(" ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setEnabled(false);
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenu1.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem3.setText("Export to CSV");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Disable Users");
        jMenuItem4.setActionCommand("Disableusers");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem1.setText("Clear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Connection Properties");
        jMenu2.setName("jmi_connectionSettings"); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Change Settings");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Browse button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        //FileFilter ff = new FileNameExtensionFilter("Log Files (*.log)", "log");
        IstiFileFilter ff = new IstiFileFilter("*.log*", "Log Files");
        fileChooser.addChoosableFileFilter(ff);
        fileChooser.setFileFilter(ff);
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = fileChooser.getSelectedFile();
            filename = selectedFile.getAbsolutePath();
            
            try
            {
                BufferedReader reader = new BufferedReader(new FileReader(filename));
                String line = reader.readLine();
                reader.close();

                if(line.matches("^.*\\p{javaSpaceChar}.*\\p{javaSpaceChar}.*\\p{javaSpaceChar}.*\\p{javaSpaceChar}ownCloud\\[.*\\].*$")) // Matches owncloud
                {
                    jTextField1.setText(filename);
                    jButton2.setEnabled(true);
                    jLabel3.setText("File selected: " + filename);
                }
                else
                {
                    filename = "";
                    JOptionPane.showMessageDialog(null, "Selected file is not an ownCloud log file.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    jLabel3.setText("ERROR: Selected file is not an ownCloud log file.");
                }
            }
            catch (Exception e)
            {
                jLabel3.setText("Error reading file");
            }
        }
        else
        {
            if(filename.equals(""))
                jLabel3.setText("File not selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Execute button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        final long startTime = System.currentTimeMillis(); // Measure how fast the algorithm is
        
        ArrayList<ArrayList<String>> records = new ArrayList<ArrayList<String>>();
        ArrayList<String> tmpRecord;
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        //
        // READ FILE
        //
        try
        {
          BufferedReader reader = new BufferedReader(new FileReader(filename));
          String line;
          String[] tmparr;

          while ((line = reader.readLine()) != null)
          {
              if(line.contains("hipaa") && line.contains("LOGIN: Failed") && !line.contains("message repeated"))
              {
                //JOptionPane.showMessageDialog(null, line, "DEBUG", JOptionPane.INFORMATION_MESSAGE);
                tmpRecord = new ArrayList<String>();
                
                // Dynamically determine the servername for the Date split()
                tmparr = line.split("\\s+");
                String hostname = tmparr[3];
                
                tmparr = line.split(" " + hostname + " ");
                tmpRecord.add(tmparr[0]); // Date
                
                tmparr = tmparr[1].split("[\\[\\]]");
                tmpRecord.add(tmparr[3]); // IP

                tmparr = tmparr[4].split("[()]");
                tmpRecord.add(tmparr[1]); // User
                
                records.add(tmpRecord);
              }
          }
          reader.close();
        }
        catch (Exception e)
        {
          jLabel3.setText("Error reading file");
          //System.err.format("Exception occurred trying to read '%s'.", filename);
          //e.printStackTrace();
          return;
        }
        
        
        //
        // LOGIC
        //
        
        // User -> Date,Date,Date,etc.  IP is ignored in the working set
        // since it can be obtained from cur.get(1).
        HashMap<String,ArrayList<String>> working = new HashMap<>();
        
        Boolean notfound = true; // To determine if already found in below loop
        
        int failThreshold;
        try
        {
            failThreshold = Integer.parseInt(jTextField2.getText());
        }
        catch (Exception e)
        {
            failThreshold = 3;
            jTextField2.setText("3");
        }
        
        int minThreshold;
        try
        {
            // Convert mins to secs to make the calc more precise
            minThreshold = Integer.parseInt(jTextField3.getText()) * 60;
        }
        catch (Exception e)
        {
            minThreshold = 300; // 5 * 60
            jTextField3.setText("5");
        }
        
        // Loop through all users read from the file
        for (ArrayList<String> cur : records)
        {
            // Verify we haven't already determined the user is bad
            notfound = true;
            if(badusers.containsKey(cur.get(2))) notfound = false;
            
            // If the user isn't already set to be disabled, run the checks...
            if(notfound)
            {
                // If user is already in the working set, add the cur date
                if(working.containsKey(cur.get(2)))
                    working.get(cur.get(2)).add(cur.get(0));
                // else PUT a new entry in the working map
                else
                    working.put(cur.get(2),new ArrayList<String>(Arrays.asList(cur.get(0))));
                    
                // Save the last (most recent) date entry for future comparisons
                SimpleDateFormat inputDateFormat = new SimpleDateFormat("MMM dd HH:mm:ss");
                Date startDate = null, curDate = null;
                try
                {
                    startDate = inputDateFormat.parse(working.get(cur.get(2)).get(working.get(cur.get(2)).size()-1));
                }
                catch (ParseException e)
                {
                    e.printStackTrace();
                }
                
                // Create a minThreshold window fail counter
                int count = 0;
                
                // Loop backwards through the date array and count dates until
                // you hit the minThreshold
                for(int x = working.get(cur.get(2)).size()-1; x >= 0; x--)
                {
                    try
                    {
                        curDate = inputDateFormat.parse(working.get(cur.get(2)).get(x));
                    }
                    catch (ParseException e)
                    {
                        e.printStackTrace();
                    }
                    long secDiff = TimeUnit.MILLISECONDS.toSeconds(startDate.getTime() - curDate.getTime());
                    
                    // if curdate is within minThreshold minutes (saved in seconds) of startDate
                    if(secDiff <= minThreshold)
                    {
                        count++;
                    
                        // If the date array contains failThreshold or more dates
                        // within the minThreshold timeframe, we have a bad user
                        if (count >= failThreshold)
                           badusers.put(cur.get(2),cur.get(1));
                    }
                    else
                        break;
                }
            }
	}
        
        // Display bad users
        for(String key : badusers.keySet())
            model.addRow(new Object[]{key, badusers.get(key)});

        final long endTime = System.currentTimeMillis(); // End time of algorithm
        jLabel3.setText("Parse complete: " + (endTime - startTime) + "ms");
        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText(Integer.toString(badusers.size()) + " bad users");
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jMenuItem3.setEnabled(true);
        jMenuItem4.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Exit menu
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Clear Menu
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTextField1.setText("");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        filename = "";
        //badusers.clear();
        badusers = null;
        badusers = new HashMap<>();
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jMenuItem3.setEnabled(false);
        jMenuItem4.setEnabled(false);
        jLabel3.setText(" ");
        jLabel4.setText(" ");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // CSV Export
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileFilter ff = new FileNameExtensionFilter("CSV Files (*.csv)", "csv");
        fileChooser.addChoosableFileFilter(ff);
        fileChooser.setFileFilter(ff);
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = fileChooser.getSelectedFile();
            filename = selectedFile.getAbsolutePath();
            
            if(!filename.matches("^.*\\.csv$"))
                filename += ".csv";
            
            try (BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(filename), "utf-8")))
            {
                for(String key : badusers.keySet())
                {
                    writer.write(key + "," + badusers.get(key));
                    writer.newLine();
                }

                jLabel3.setText("CSV export: success");
            }
            catch(IOException e)
            {
                //e.printStackTrace();
                jLabel3.setText("CSV export: error");
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        String username = jdlg_dbSettings.getDBUserName();
        String password = new String (jdlg_dbSettings.getDBUserPwd());        
        String database = jdlg_dbSettings.getDBDatabaseName();
        String databaseAddress = "jdbc:mysql://" + jdlg_dbSettings.getDBHostName();
        
        //Disableusers.setVisible(false);
        Connection con = null;
        PreparedStatement pst = null;
        
        try {

            //String author = "Trygve Gulbranssen";
            Driver mysqlDriver = new com.mysql.jdbc.Driver ();
            con = DriverManager.getConnection(databaseAddress, username, password);
            
            PreparedStatement selectOwncloud = con.prepareStatement ("use " + database);
            selectOwncloud.executeUpdate ();
            
            int updated = 0;
            
            for (String key : badusers.keySet()){
                
                //model.addRow(new Object[]{key, badusers.get(key)});
                pst = con.prepareStatement("INSERT INTO oc_preferences(userid, appid, configkey, configvalue) VALUES(?, ?, ?, ?)");
                
                pst.setString(1, key);                
                pst.setString(2, "core");
                pst.setString(3, "enabled");
                pst.setString(4, "false");
                
                updated += pst.executeUpdate();
            }
            
            String alertString = "Added " + badusers.keySet().size() + " users to disabled list\n";
            alertString += "MySQL rows affected: " + updated;
            
            JOptionPane.showMessageDialog (null, alertString, "Success!", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog (null, "SQL Exception: " + ex.toString (), "SQL ERROR!", JOptionPane.ERROR_MESSAGE);

        } finally {

            try {
                
                if (pst != null) {
                    pst.close();
                }
                
                if (con != null) {
                    con.close();
                }

            } catch (SQLException ex) {
                
                JOptionPane.showMessageDialog (null, "SQL Exception: " + ex.toString (), "SQL ERROR!", JOptionPane.ERROR_MESSAGE);
            }
    
         }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
        jdlg_dbSettings.setVisible (true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogParser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogParser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}

class DBConnectSettingsDialog extends JDialog implements ActionListener {

    private JTextField jtf_username;
    private JPasswordField jpf_password;
    private JTextField jtf_dbname;
    private JTextField jtf_hostname;
    
    private JButton jbtn_apply;
    private JButton jbtn_cancel;
    
    private boolean saveChanges;
    
    private static final char [] MASTER_PWD = "kjojiojaowe933e2".toCharArray();
    private static final byte [] PWD_SALT = { (byte) 0x12, (byte) 0x45, (byte) 0x23, (byte) 0x55, 
            (byte)0x12, (byte)(0x45), (byte)0x23, (byte) 0x55 };
    
    public DBConnectSettingsDialog () {
        
        // initialize components and load configuration file
        initComponents ();
        
        // if the configuration file does not exist, ask if we should create it.
        // if not, changes to the connection settings will NOT be saved and
        // a default connection will be loaded
        if (!(new File("config.dat")).exists()) {
                       
            jtf_username.setText ("root");
            jpf_password.setText ("");
            jtf_dbname.setText ("owncloud");
            jtf_hostname.setText ("localhost");
                    
            try { writeConfigFile (); }
                
            catch (IOException e) {
                    
                JOptionPane.showMessageDialog (null, "Configuration file could not be written. Changes will NOT be saved!",
                       "File Error:", JOptionPane.ERROR_MESSAGE);
                    
                // if there was an I/O error but the file exists, delete the file
                File configFile = new File ("config.dat");
                if (configFile.exists())
                    configFile.delete();
            }
        }
        
        // the file already exists, load the configuration
        else {
            
            try {
                
                loadConfigFile ();

            } catch (IOException e) {
                
            }
        }
    }
    
    public String getDBUserName () { return jtf_username.getText(); }
    public char [] getDBUserPwd () { return jpf_password.getPassword(); }
    public String getDBDatabaseName () { return jtf_dbname.getText(); }
    public String getDBHostName () { return jtf_hostname.getText(); }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
       
        if (ae.getSource () == jbtn_apply) {
            
            try {
                
                writeConfigFile ();
            
            } catch (IOException e) {
               
                JOptionPane.showMessageDialog (null, "Unable to write configuration file", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        else if (ae.getSource () == jbtn_cancel) {
            
            try {
                
                loadConfigFile ();
            
            } catch (IOException ex) {
                
                Logger.getLogger(DBConnectSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.setVisible (false);
    }
    
    private void initComponents () {
        
        // create a new border layout
        this.setLayout (new GridBagLayout ());
        GridBagConstraints gbc = new GridBagConstraints ();
        gbc.insets = new Insets (5, 5, 5, 5);
        
        // create a label for the username field, then the field
        jtf_username = new JTextField ();
        jpf_password = new JPasswordField ();
        jtf_dbname = new JTextField ();
        jtf_hostname = new JTextField ();
        
        jbtn_apply = new JButton ("Apply Settings");
        jbtn_apply.addActionListener(this);
        
        jbtn_cancel = new JButton ("Cancel");
        jbtn_cancel.addActionListener (this);
        
        // set up to add the labels
        gbc.gridwidth = 2;
        gbc.weightx = 0.1;
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        // add the username label
        this.add (new JLabel("Username:"), gbc);
        // add the password label
        gbc.gridy = 1;
        this.add (new JLabel ("Password:"), gbc);
        // add the db name label
        gbc.gridy = 2;
        this.add (new JLabel ("Database name:"), gbc);
        // add the hostname label
        gbc.gridy = 3;
        this.add (new JLabel ("Host name / IP:"), gbc);
        
        // reset for adding the text fields
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        this.add (jtf_username, gbc);
        gbc.gridy = 1;
        this.add (jpf_password, gbc);
        gbc.gridy = 2;
        this.add (jtf_dbname, gbc);
        gbc.gridy = 3;
        this.add (jtf_hostname, gbc);
        
        // reset for adding the buttons
        gbc.gridwidth = 2;
        gbc.weightx = 0.1;
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.NONE;
        
        // add the buttons
        gbc.anchor = GridBagConstraints.PAGE_END;
        this.add (jbtn_apply, gbc);
        
        gbc.anchor = GridBagConstraints.PAGE_END;
        gbc.gridx = 4;
        gbc.gridwidth = 1;
        
        this.add (jbtn_cancel, gbc);
        
        // try to size the two buttons the same
        jbtn_cancel.setPreferredSize(jbtn_apply.getPreferredSize());

        // show this dialog (testing!!!)
        this.setSize (400, 300);
        this.setModal(true);
        this.setTitle ("Connection Properties");
    }
    
    private void loadConfigFile () throws IOException {
      
        try (BufferedReader cfgReader = new BufferedReader (new InputStreamReader (new FileInputStream ("config.dat")))) {
            
            // read the first line, should be [db_config]
            if (!cfgReader.readLine().equals ("db_config"))
                throw new IOException ("Invalid configuration file format");
            
            String curLine = "";
            
            while ((curLine = cfgReader.readLine ()) != null) {
                
                // read each setting in
                
                // get the username from the file
                if (curLine.startsWith ("username=")) {
                    
                    String uname = curLine.substring (curLine.indexOf('=')+1);
                    jtf_username.setText (uname);
                }
                
                // get the password from the file
                else if (curLine.startsWith("password=")) {
                    
                    try {
                    
                        String pwd = curLine.substring (curLine.indexOf('=')+1, curLine.length());
                        pwd = decryptPassword (pwd);
                        jpf_password.setText (pwd);
                        
                    } catch (GeneralSecurityException ex) {
                        
                    }
                }
                
                else if (curLine.startsWith ("default-db=")) {
                    
                    String dbname = curLine.substring (curLine.indexOf('=')+1);
                    jtf_dbname.setText (dbname);
                }
                
                else if (curLine.startsWith ("host-id=")) {
                    
                    String hostid = curLine.substring (curLine.indexOf('=')+1);
                    jtf_hostname.setText (hostid);
                }
                
                else {
                    
                    System.out.println ("Invalid setting, skipping...");
                }
            }
            
            // close the reader
            cfgReader.close ();      
        }
    }
    
    private void writeConfigFile () throws IOException {
         
        // write the new configuration file
        try (BufferedWriter cfgWriter = new BufferedWriter (new OutputStreamWriter (new FileOutputStream ("config.dat")))) 
        {
            cfgWriter.write ("db_config\n");
            cfgWriter.write ("username=" + jtf_username.getText() + "\n");
            
            try {
                
                cfgWriter.write ("password=" + encryptPassword(jpf_password.getText()) + "\n");
                
            } catch (GeneralSecurityException | UnsupportedEncodingException ex) {
                
                Logger.getLogger(DBConnectSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            cfgWriter.write ("default-db=" + jtf_dbname.getText() + "\n");
            cfgWriter.write ("host-id=" + jtf_hostname.getText() + "\n");

            cfgWriter.flush ();
            cfgWriter.close ();
        }
    }
    
    private String encryptPassword (String pwd) throws GeneralSecurityException, UnsupportedEncodingException {
        
        SecretKeyFactory keyFactory = SecretKeyFactory.getInstance ("PBEWithMD5AndDES");
        SecretKey key = keyFactory.generateSecret (new PBEKeySpec (MASTER_PWD));
        
        Cipher pbeCipher = Cipher.getInstance ("PBEWithMD5AndDES");
        pbeCipher.init (Cipher.ENCRYPT_MODE, key, new PBEParameterSpec(PWD_SALT, 20));
        
        String baseEncode = new BASE64Encoder().encode(pbeCipher.doFinal(pwd.getBytes("UTF-8")));
        return baseEncode;
    }
    
    private String decryptPassword (String pwd) throws GeneralSecurityException, IOException {
        
        SecretKeyFactory keyFactory = SecretKeyFactory.getInstance ("PBEWithMD5AndDES");
        SecretKey key = keyFactory.generateSecret (new PBEKeySpec (MASTER_PWD));
        
        Cipher pbeCipher = Cipher.getInstance ("PBEWithMD5AndDES");
        pbeCipher.init (Cipher.DECRYPT_MODE, key, new PBEParameterSpec(PWD_SALT, 20));
        
        return new String (pbeCipher.doFinal (new BASE64Decoder().decodeBuffer(pwd)));
    }
}